export type ElementMap = {
  langToggle: HTMLButtonElement;
  topbarSubtitle: HTMLElement;
  lblActiveTrip: HTMLElement;
  btnDetectedCurrencyPill: HTMLButtonElement;
  tripSelect: HTMLSelectElement;
  editTripSection: HTMLElement;
  sumEditTrip: HTMLElement;
  editTripForm: HTMLFormElement;
  lblEditTripTitle: HTMLElement;
  editTripTitle: HTMLInputElement;
  lblEditTripStart: HTMLElement;
  editTripStart: HTMLInputElement;
  lblEditTripEnd: HTMLElement;
  editTripEnd: HTMLInputElement;
  lblEditTripDestinations: HTMLElement;
  editTripDestinations: HTMLInputElement;
  lblEditTripTags: HTMLElement;
  editTripTags: HTMLInputElement;
  lblEditTripCurrency: HTMLElement;
  editTripCurrency: HTMLInputElement;
  lblEditTripTransport: HTMLElement;
  editTripTransport: HTMLSelectElement;
  btnSaveTripEdit: HTMLButtonElement;
  btnDeleteTrip: HTMLButtonElement;
  createTripSection: HTMLElement;
  sumCreateTrip: HTMLElement;
  tripForm: HTMLFormElement;
  lblTripTitle: HTMLElement;
  tripTitle: HTMLInputElement;
  lblTripStart: HTMLElement;
  tripStart: HTMLInputElement;
  lblTripEnd: HTMLElement;
  tripEnd: HTMLInputElement;
  lblTripDestinations: HTMLElement;
  tripDestinations: HTMLInputElement;
  lblTripTags: HTMLElement;
  tripTags: HTMLInputElement;
  lblTripCurrency: HTMLElement;
  tripCurrency: HTMLInputElement;
  lblTripTransport: HTMLElement;
  tripTransport: HTMLSelectElement;
  btnCreateTrip: HTMLButtonElement;
  bulkImportSection: HTMLElement;
  sumBulkImport: HTMLElement;
  lblBulkText: HTMLElement;
  bulkInputText: HTMLTextAreaElement;
  btnParseBulkImport: HTMLButtonElement;
  smartListSection: HTMLElement;
  smartListBadge: HTMLElement;
  smartListCountBadge: HTMLElement;
  smartListTitle: HTMLElement;
  smartListDesc: HTMLElement;
  btnSmartSyncAll: HTMLButtonElement;
  btnToggleListPreview: HTMLButtonElement;
  smartListPreviewContainer: HTMLElement;
  batchListContainer: HTMLElement;
  btnToggleSelectAll: HTMLButtonElement;
  btnBatchAdd: HTMLButtonElement;
  lblCurrentPlace: HTMLElement;
  btnDismissPlace: HTMLButtonElement;
  placeTitle: HTMLElement;
  placeUrl: HTMLElement;
  placeCapturedBanner: HTMLElement;
  txtCapturedBanner: HTMLElement;
  placeMetaBadges: HTMLElement;
  refreshPlace: HTMLButtonElement;
  captureForm: HTMLFormElement;
  lblKind: HTMLElement;
  kind: HTMLSelectElement;
  lblPriority: HTMLElement;
  priority: HTMLSelectElement;
  lblArea: HTMLElement;
  area: HTMLInputElement;
  lblTags: HTMLElement;
  tags: HTMLInputElement;
  lblDuration: HTMLElement;
  duration: HTMLInputElement;
  lblWindow: HTMLElement;
  window: HTMLInputElement;
  lblRating: HTMLElement;
  rating: HTMLInputElement;
  lblPrice: HTMLElement;
  price: HTMLInputElement;
  lblQuickChips: HTMLElement;
  quickChips: HTMLElement;
  lblWhy: HTMLElement;
  why: HTMLTextAreaElement;
  captureAdvanced: HTMLDetailsElement;
  captureAdvancedSummary: HTMLElement;
  lblSignals: HTMLElement;
  signals: HTMLInputElement;
  lblRisks: HTMLElement;
  risks: HTMLInputElement;
  lblNotes: HTMLElement;
  notes: HTMLTextAreaElement;
  btnCaptureSubmit: HTMLButtonElement;
  btnRemoveCandidate: HTMLButtonElement;
  candidatesDrawer: HTMLElement;
  sumCandidatesDrawer: HTMLElement;
  candidatesCountBadge: HTMLElement;
  candidatesSearch: HTMLInputElement;
  candidatesFilterBar: HTMLElement;
  candidatesListContainer: HTMLElement;
  pending: HTMLElement;
  status: HTMLElement;
};

export function required<T extends HTMLElement>(id: string): T {
  const node = document.getElementById(id);
  if (!node) throw new Error(`Missing Ownly Capture element: ${id}`);
  return node as T;
}

export const el: ElementMap = {
  langToggle: required('langToggle'),
  topbarSubtitle: required('topbarSubtitle'),
  lblActiveTrip: required('lblActiveTrip'),
  btnDetectedCurrencyPill: required('btnDetectedCurrencyPill'),
  tripSelect: required('tripSelect'),
  editTripSection: required('editTripSection'),
  sumEditTrip: required('sumEditTrip'),
  editTripForm: required('editTripForm'),
  lblEditTripTitle: required('lblEditTripTitle'),
  editTripTitle: required('editTripTitle'),
  lblEditTripStart: required('lblEditTripStart'),
  editTripStart: required('editTripStart'),
  lblEditTripEnd: required('lblEditTripEnd'),
  editTripEnd: required('editTripEnd'),
  lblEditTripDestinations: required('lblEditTripDestinations'),
  editTripDestinations: required('editTripDestinations'),
  lblEditTripTags: required('lblEditTripTags'),
  editTripTags: required('editTripTags'),
  lblEditTripCurrency: required('lblEditTripCurrency'),
  editTripCurrency: required('editTripCurrency'),
  lblEditTripTransport: required('lblEditTripTransport'),
  editTripTransport: required('editTripTransport'),
  btnSaveTripEdit: required('btnSaveTripEdit'),
  btnDeleteTrip: required('btnDeleteTrip'),
  createTripSection: required('createTripSection'),
  sumCreateTrip: required('sumCreateTrip'),
  tripForm: required('tripForm'),
  lblTripTitle: required('lblTripTitle'),
  tripTitle: required('tripTitle'),
  lblTripStart: required('lblTripStart'),
  tripStart: required('tripStart'),
  lblTripEnd: required('lblTripEnd'),
  tripEnd: required('tripEnd'),
  lblTripDestinations: required('lblTripDestinations'),
  tripDestinations: required('tripDestinations'),
  lblTripTags: required('lblTripTags'),
  tripTags: required('tripTags'),
  lblTripCurrency: required('lblTripCurrency'),
  tripCurrency: required('tripCurrency'),
  lblTripTransport: required('lblTripTransport'),
  tripTransport: required('tripTransport'),
  btnCreateTrip: required('btnCreateTrip'),
  bulkImportSection: required('bulkImportSection'),
  sumBulkImport: required('sumBulkImport'),
  lblBulkText: required('lblBulkText'),
  bulkInputText: required('bulkInputText'),
  btnParseBulkImport: required('btnParseBulkImport'),
  smartListSection: required('smartListSection'),
  smartListBadge: required('smartListBadge'),
  smartListCountBadge: required('smartListCountBadge'),
  smartListTitle: required('smartListTitle'),
  smartListDesc: required('smartListDesc'),
  btnSmartSyncAll: required('btnSmartSyncAll'),
  btnToggleListPreview: required('btnToggleListPreview'),
  smartListPreviewContainer: required('smartListPreviewContainer'),
  batchListContainer: required('batchListContainer'),
  btnToggleSelectAll: required('btnToggleSelectAll'),
  btnBatchAdd: required('btnBatchAdd'),
  lblCurrentPlace: required('lblCurrentPlace'),
  btnDismissPlace: required('btnDismissPlace'),
  placeTitle: required('placeTitle'),
  placeUrl: required('placeUrl'),
  placeCapturedBanner: required('placeCapturedBanner'),
  txtCapturedBanner: required('txtCapturedBanner'),
  placeMetaBadges: required('placeMetaBadges'),
  refreshPlace: required('refreshPlace'),
  captureForm: required('captureForm'),
  lblKind: required('lblKind'),
  kind: required('kind'),
  lblPriority: required('lblPriority'),
  priority: required('priority'),
  lblArea: required('lblArea'),
  area: required('area'),
  lblTags: required('lblTags'),
  tags: required('tags'),
  lblDuration: required('lblDuration'),
  duration: required('duration'),
  lblWindow: required('lblWindow'),
  window: required('window'),
  lblRating: required('lblRating'),
  rating: required('rating'),
  lblPrice: required('lblPrice'),
  price: required('price'),
  lblQuickChips: required('lblQuickChips'),
  quickChips: required('quickChips'),
  lblWhy: required('lblWhy'),
  why: required('why'),
  captureAdvanced: required<HTMLDetailsElement>('captureAdvanced'),
  captureAdvancedSummary: required('captureAdvancedSummary'),
  lblSignals: required('lblSignals'),
  signals: required('signals'),
  lblRisks: required('lblRisks'),
  risks: required('risks'),
  lblNotes: required('lblNotes'),
  notes: required('notes'),
  btnCaptureSubmit: required('btnCaptureSubmit'),
  btnRemoveCandidate: required('btnRemoveCandidate'),
  candidatesDrawer: required('candidatesDrawer'),
  sumCandidatesDrawer: required('sumCandidatesDrawer'),
  candidatesCountBadge: required('candidatesCountBadge'),
  candidatesSearch: required('candidatesSearch'),
  candidatesFilterBar: required('candidatesFilterBar'),
  candidatesListContainer: required('candidatesListContainer'),
  pending: required('pending'),
  status: required('status'),
};
