export type ElementMap = {
  langToggle: HTMLButtonElement;
  toggleFxTooltip: HTMLInputElement;
  lblFxTooltipToggle: HTMLElement;
  txtFxTooltipToggle: HTMLElement;
  toggleDebugMode: HTMLInputElement;
  lblDebugToggle: HTMLElement;
  txtDebugToggle: HTMLElement;
  lblActiveTrip: HTMLElement;
  captureContextTitle: HTMLElement;
  captureContextHint: HTMLElement;
  pageCurrencyBar: HTMLElement;
  currencySelector: HTMLSelectElement;
  btnRedetectCurrency: HTMLButtonElement;
  sumBulkImport: HTMLElement;
  lblBulkText: HTMLElement;
  bulkInputText: HTMLTextAreaElement;
  btnParseBulkImport: HTMLButtonElement;
  btnShareCollection: HTMLButtonElement;
  btnExportCollection: HTMLButtonElement;
  btnBackupState: HTMLButtonElement;
  btnRestoreState: HTMLButtonElement;
  fileRestoreState: HTMLInputElement;
  btnBulkToggle: HTMLButtonElement;
  btnEnrichCandidates: HTMLButtonElement;
  btnImportToPlanner: HTMLButtonElement;
  bulkActionBar: HTMLElement;
  bulkPrioritySelect: HTMLSelectElement;
  btnSelectAllCandidates: HTMLButtonElement;
  btnBulkEnrich: HTMLButtonElement;
  btnBulkDelete: HTMLButtonElement;
  btnBulkExit: HTMLButtonElement;
  smartListSection: HTMLElement;
  smartListBadge: HTMLElement;
  smartListCountBadge: HTMLElement;
  smartListTitle: HTMLElement;
  smartListDesc: HTMLElement;
  btnSmartSyncAll: HTMLButtonElement;
  btnCloseSmartList: HTMLButtonElement;
  btnToggleListPreview: HTMLButtonElement;
  smartListPreviewContainer: HTMLElement;
  batchListContainer: HTMLElement;
  btnToggleSelectAll: HTMLButtonElement;
  btnBatchAdd: HTMLButtonElement;
  lblCurrentPlace: HTMLElement;
  btnDismissPlace: HTMLButtonElement;
  placeTitle: HTMLElement;
  placeUrl: HTMLElement;
  placeCapturedBanner: HTMLElement;
  txtCapturedBanner: HTMLElement;
  placeMetaBadges: HTMLElement;
  refreshPlace: HTMLButtonElement;
  placePanel: HTMLElement;
  placeProvider: HTMLElement;
  captureForm: HTMLFormElement;
  lblKind: HTMLElement;
  kind: HTMLSelectElement;
  lblArea: HTMLElement;
  area: HTMLInputElement;
  lblTags: HTMLElement;
  tags: HTMLInputElement;
  lblDuration: HTMLElement;
  duration: HTMLInputElement;
  lblWindow: HTMLElement;
  window: HTMLInputElement;
  lblRating: HTMLElement;
  rating: HTMLInputElement;
  lblPrice: HTMLElement;
  price: HTMLInputElement;
  lblQuickChips: HTMLElement;
  quickChips: HTMLElement;
  lblWhy: HTMLElement;
  why: HTMLTextAreaElement;
  captureAdvanced: HTMLDetailsElement;
  captureAdvancedSummary: HTMLElement;
  lblSignals: HTMLElement;
  signals: HTMLInputElement;
  lblRisks: HTMLElement;
  risks: HTMLInputElement;
  lblNotes: HTMLElement;
  notes: HTMLTextAreaElement;
  btnCaptureSubmit: HTMLButtonElement;
  btnRemoveCandidate: HTMLButtonElement;
  candidatesDrawer: HTMLDetailsElement;
  sumCandidatesDrawer: HTMLElement;
  candidatesCountBadge: HTMLElement;
  candidatesSearch: HTMLInputElement;
  candidatesFilterBar: HTMLElement;
  candidatesListContainer: HTMLElement;
  pending: HTMLElement;
  status: HTMLElement;
  debugDrawer: HTMLDetailsElement;
  sumDebugDrawer: HTMLElement;
  btnCopyDebugLogs: HTMLButtonElement;
  btnExportDiagnostics: HTMLButtonElement;
  btnCopyAIDiagnostics: HTMLButtonElement;
  btnClearDebugLogs: HTMLButtonElement;
  debugLogViewer: HTMLElement;
  importReportBanner: HTMLElement;
  importReportIcon: HTMLElement;
  importReportTitle: HTMLElement;
  importReportDismiss: HTMLButtonElement;
  importReportStats: HTMLElement;
  importReportFailed: HTMLElement;
};

export function required<T extends HTMLElement>(id: string): T {
  const node = document.getElementById(id);
  if (!node) throw new Error(`Missing Ownly Capture element: ${id}`);
  return node as T;
}

export const el: ElementMap = {
  langToggle: required('langToggle'),
  toggleFxTooltip: required<HTMLInputElement>('toggleFxTooltip'),
  lblFxTooltipToggle: required('lblFxTooltipToggle'),
  txtFxTooltipToggle: required('txtFxTooltipToggle'),
  toggleDebugMode: required<HTMLInputElement>('toggleDebugMode'),
  lblDebugToggle: required('lblDebugToggle'),
  txtDebugToggle: required('txtDebugToggle'),
  lblActiveTrip: required('lblActiveTrip'),
  captureContextTitle: required('captureContextTitle'),
  captureContextHint: required('captureContextHint'),
  pageCurrencyBar: required('pageCurrencyBar'),
  currencySelector: required<HTMLSelectElement>('currencySelector'),
  btnRedetectCurrency: required<HTMLButtonElement>('btnRedetectCurrency'),
  sumBulkImport: required('sumBulkImport'),
  lblBulkText: required('lblBulkText'),
  bulkInputText: required<HTMLTextAreaElement>('bulkInputText'),
  btnParseBulkImport: required<HTMLButtonElement>('btnParseBulkImport'),
  btnShareCollection: required<HTMLButtonElement>('btnShareCollection'),
  btnExportCollection: required<HTMLButtonElement>('btnExportCollection'),
  btnBackupState: required<HTMLButtonElement>('btnBackupState'),
  btnRestoreState: required<HTMLButtonElement>('btnRestoreState'),
  fileRestoreState: required<HTMLInputElement>('fileRestoreState'),
  btnBulkToggle: required<HTMLButtonElement>('btnBulkToggle'),
  btnEnrichCandidates: required<HTMLButtonElement>('btnEnrichCandidates'),
  btnImportToPlanner: required<HTMLButtonElement>('btnImportToPlanner'),
  bulkActionBar: required('bulkActionBar'),
  bulkPrioritySelect: required<HTMLSelectElement>('bulkPrioritySelect'),
  btnSelectAllCandidates: required<HTMLButtonElement>('btnSelectAllCandidates'),
  btnBulkEnrich: required<HTMLButtonElement>('btnBulkEnrich'),
  btnBulkDelete: required<HTMLButtonElement>('btnBulkDelete'),
  btnBulkExit: required<HTMLButtonElement>('btnBulkExit'),
  smartListSection: required('smartListSection'),
  smartListBadge: required('smartListBadge'),
  smartListCountBadge: required('smartListCountBadge'),
  smartListTitle: required('smartListTitle'),
  smartListDesc: required('smartListDesc'),
  btnSmartSyncAll: required<HTMLButtonElement>('btnSmartSyncAll'),
  btnCloseSmartList: required<HTMLButtonElement>('btnCloseSmartList'),
  btnToggleListPreview: required<HTMLButtonElement>('btnToggleListPreview'),
  smartListPreviewContainer: required('smartListPreviewContainer'),
  batchListContainer: required('batchListContainer'),
  btnToggleSelectAll: required<HTMLButtonElement>('btnToggleSelectAll'),
  btnBatchAdd: required<HTMLButtonElement>('btnBatchAdd'),
  lblCurrentPlace: required('lblCurrentPlace'),
  btnDismissPlace: required<HTMLButtonElement>('btnDismissPlace'),
  placeTitle: required('placeTitle'),
  placeUrl: required('placeUrl'),
  placeCapturedBanner: required('placeCapturedBanner'),
  txtCapturedBanner: required('txtCapturedBanner'),
  placeMetaBadges: required('placeMetaBadges'),
  refreshPlace: required<HTMLButtonElement>('refreshPlace'),
  placePanel: required('placePanel'),
  placeProvider: required('placeProvider'),
  captureForm: required<HTMLFormElement>('captureForm'),
  lblKind: required('lblKind'),
  kind: required<HTMLSelectElement>('kind'),
  lblArea: required('lblArea'),
  area: required<HTMLInputElement>('area'),
  lblTags: required('lblTags'),
  tags: required<HTMLInputElement>('tags'),
  lblDuration: required('lblDuration'),
  duration: required<HTMLInputElement>('duration'),
  lblWindow: required('lblWindow'),
  window: required<HTMLInputElement>('window'),
  lblRating: required('lblRating'),
  rating: required<HTMLInputElement>('rating'),
  lblPrice: required('lblPrice'),
  price: required<HTMLInputElement>('price'),
  lblQuickChips: required('lblQuickChips'),
  quickChips: required('quickChips'),
  lblWhy: required('lblWhy'),
  why: required<HTMLTextAreaElement>('why'),
  captureAdvanced: required<HTMLDetailsElement>('captureAdvanced'),
  captureAdvancedSummary: required('captureAdvancedSummary'),
  lblSignals: required('lblSignals'),
  signals: required<HTMLInputElement>('signals'),
  lblRisks: required('lblRisks'),
  risks: required<HTMLInputElement>('risks'),
  lblNotes: required('lblNotes'),
  notes: required<HTMLTextAreaElement>('notes'),
  btnCaptureSubmit: required<HTMLButtonElement>('btnCaptureSubmit'),
  btnRemoveCandidate: required<HTMLButtonElement>('btnRemoveCandidate'),
  candidatesDrawer: required<HTMLDetailsElement>('candidatesDrawer'),
  sumCandidatesDrawer: required('sumCandidatesDrawer'),
  candidatesCountBadge: required('candidatesCountBadge'),
  candidatesSearch: required<HTMLInputElement>('candidatesSearch'),
  candidatesFilterBar: required('candidatesFilterBar'),
  candidatesListContainer: required('candidatesListContainer'),
  pending: required('pending'),
  status: required('status'),
  debugDrawer: required<HTMLDetailsElement>('debugDrawer'),
  sumDebugDrawer: required('sumDebugDrawer'),
  btnCopyDebugLogs: required<HTMLButtonElement>('btnCopyDebugLogs'),
  btnExportDiagnostics: required<HTMLButtonElement>('btnExportDiagnostics'),
  btnCopyAIDiagnostics: required<HTMLButtonElement>('btnCopyAIDiagnostics'),
  btnClearDebugLogs: required<HTMLButtonElement>('btnClearDebugLogs'),
  debugLogViewer: required('debugLogViewer'),
  importReportBanner: required('importReportBanner'),
  importReportIcon: required('importReportIcon'),
  importReportTitle: required('importReportTitle'),
  importReportDismiss: required<HTMLButtonElement>('importReportDismiss'),
  importReportStats: required('importReportStats'),
  importReportFailed: required('importReportFailed'),
};
