'use client';

/**
 * Runtime loader for the Sample Data set.
 *
 * The dataset is inert JSON with no runtime imports, so it ships as a static
 * file under `public/` and is fetched on demand rather than bundled. That keeps
 * ~28 KB of records out of every route's JS payload and avoids depending on a
 * bundler's dynamic-import runtime for data that has no dependencies of its
 * own — which is the one thing a dynamic import is a poor fit for.
 *
 * `public/sample-data/ledger.json` is the single source of truth and is
 * regenerated by `scripts/emit-sample-data.mjs`.
 */
import type { SampleDataSet } from './ledger-types';

export const SAMPLE_DATA_URL = 'sample-data/ledger.json';

const basePath = process.env.NEXT_PUBLIC_OWNLY_BASE_PATH ?? '';

/**
 * Shape check rather than a type assertion: a truncated or hand-edited file
 * must fail loudly here instead of surfacing as a half-empty dashboard.
 */
export function assertSampleDataShape(value: unknown): SampleDataSet {
  const data = value as Partial<SampleDataSet> | null;
  if (!data || typeof data !== 'object') {
    throw new Error('Sample Data file is not an object.');
  }
  const buckets: Array<[string, unknown]> = [
    ['objects', data.objects],
    ['snapshots', data.snapshots],
    ['reviews', data.reviews],
  ];
  for (const [name, bucket] of buckets) {
    if (!Array.isArray(bucket)) throw new Error(`Sample Data file is missing "${name}".`);
  }
  if (data.bodies === null || typeof data.bodies !== 'object') {
    throw new Error('Sample Data file is missing "bodies".');
  }
  if (data.objects!.length === 0) throw new Error('Sample Data contains no objects.');
  if (data.snapshots!.length === 0) throw new Error('Sample Data contains no snapshots.');
  return data as SampleDataSet;
}

/** Structural subset of `Response`, so Node tests can supply a minimal stub. */
export interface SampleDataResponse {
  ok: boolean;
  status: number;
  json(): Promise<unknown>;
}

export type SampleDataFetcher = (url: string) => Promise<SampleDataResponse>;

export interface FetchSampleDataOptions {
  /** Override the request URL (tests, non-browser hosts). */
  url?: string;
  /** Override the transport (Node tests have no relative-URL fetch). */
  fetcher?: SampleDataFetcher;
}

let cached: SampleDataSet | null = null;

export async function fetchSampleData(options: FetchSampleDataOptions = {}): Promise<SampleDataSet> {
  if (cached && !options.fetcher) return cached;
  const url = options.url ?? `${basePath}/${SAMPLE_DATA_URL}`;
  // Call through an arrow rather than holding a reference to `globalThis.fetch`:
  // a detached `fetch` has no receiver, and in Chromium the call then never
  // dispatches — the promise simply never settles, with no console error and no
  // network request. Going through a property access at call time keeps the
  // receiver bound.
  const fetcher = options.fetcher ?? ((target: string) => globalThis.fetch(target));
  const response = await fetcher(url);
  if (!response.ok) {
    throw new Error(`Could not load Sample Data (HTTP ${response.status}).`);
  }
  const parsed = assertSampleDataShape(await response.json());
  if (!options.fetcher) cached = parsed;
  return parsed;
}

/** Test seam. */
export function clearSampleDataCache(): void {
  cached = null;
}